
project_id = "vcacfysfjgoahledqdwa"

[api]
enabled = true
port = 54321
types = "./types.ts"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["https://localhost:5173"]
enable_confirm_signup = false

[auth.email]
enable_signup = true

[functions]
[functions.xero-webhook]
verify_jwt = false
