
project_id = "vcacfysfjgoahledqdwa"

[functions."xero-member-sync"]
verify_jwt = true

[functions."xero-create-contact"]
verify_jwt = true

[functions."xero-update-contact"]
verify_jwt = true

[functions."xero-get-syncable-members"]
verify_jwt = true
