
project_id = "vcacfysfjgoahledqdwa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://www.thepuzzleboss.com"
additional_redirect_urls = ["https://loving-husky-78.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
password_min_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.get-all-users]
verify_jwt = false

[functions.admin-update-roles]
verify_jwt = false

[functions.admin-email-users]
verify_jwt = false

[functions.set-admin-role]
verify_jwt = false

[functions.handle_user_signin]
verify_jwt = false

[functions.get-opensupports-token]
verify_jwt = false

[functions.count-segmented-users]
verify_jwt = false

[functions.admin-puzzle-files]
verify_jwt = false
