
project_id = "vcacfysfjgoahledqdwa"

[api]
enabled = true
port = 54321
url = "http://localhost:54321"

[db]
port = 54322

[studio]
enabled = true
port = 54323
url = "http://localhost:54323"

[inbucket]
enabled = true
port = 54324
url = "http://localhost:54324"

[storage]
enabled = true

[auth]
enabled = true
url = "http://localhost:54321"

[functions]
[functions.security-config]
verify_jwt = true

[functions.security-cookies]
verify_jwt = false

[functions.security-events]
verify_jwt = true

[functions.handle_user_signin]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.get-all-users]
verify_jwt = true

[functions.auth-manager]
verify_jwt = false

[functions.rbac-manager]
verify_jwt = true

[functions.admin-auth]
verify_jwt = true

[realtime]
enabled = true
