
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallbacks
const SUPABASE_URL = "https://vcacfysfjgoahledqdwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjYWNmeXNmamdvYWhsZWRxZHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDI3MDgsImV4cCI6MjA1OTk3ODcwOH0.sSWBAAsoofM3b-aLNseRtXhNulg6kaGqXTcXRVd_IWo";

// Implement the Singleton pattern for the Supabase client
// This ensures we only create one instance throughout the app
let instance: ReturnType<typeof createClient<Database>> | null = null;

/**
 * Returns a Supabase client instance configured with auth persistence settings
 * This follows the Singleton pattern to ensure only one client exists
 */
export function getSupabaseClient() {
  if (instance) return instance;
  
  // Create the client with proper auth configuration for persistence
  instance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage,
    },
  });
  
  return instance;
}

// For backward compatibility with existing code
export const supabase = getSupabaseClient();
